import styles from "./Inicio.module.css";

function Inicio() {
  return (
    <main>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
      <div>d</div>
    </main>
  );
}

export default Inicio;
